<a href="https://colab.research.google.com/github/Dilan-Sazan/data-analytics/blob/main/numpy_pratik.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/drive/MyDrive/veri_setleri/Student_Performance_Dataset.csv')
df.head()

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail
0,S0001,15,Male,12,1.0,65,Postgraduate,No,No,40,39,72,81,50.33,Average,Pass
1,S0002,19,Female,9,1.6,58,Graduate,No,Yes,80,44,35,47,53.00,Average,Pass
2,S0003,14,Female,12,3.6,64,High School,Yes,Yes,83,73,59,58,71.67,Good,Pass
3,S0004,18,Female,9,5.5,68,Postgraduate,Yes,No,68,48,77,54,64.33,Average,Pass
4,S0005,14,Male,10,5.0,80,High School,Yes,No,41,46,36,68,41.00,Poor,Fail

In [19]:
study_hours = df['Study_Hours_Per_Day'].values   # veya np.array(df['Study_Hours_Per_Day'])
print(type(study_hours))   # numpy.ndarray
print(study_hours.shape, study_hours.ndim, study_hours.dtype)

<class 'numpy.ndarray'>
(5000,) 1 float64

In [20]:
print(study_hours[0])       # ilk öğrencinin çalışma saati
print(study_hours[:5])      # ilk 5 öğrenci
print(study_hours[-1])      # son öğrenci

1.0
[1.  1.6 3.6 5.5 5. ]
2.0

In [21]:
kosul = study_hours > 5
print(study_hours[kosul])          # günde 5 saatten fazla çalışanlar
print(df[study_hours > 5])         # bu öğrencilerin tüm satırlarını da görebilirsin

[5.5 5.2 5.7 5.7 5.5 5.3 5.1 5.2 5.3 5.3 5.4 5.8 5.7 5.7 5.6 5.8 5.3 5.1
 5.3 5.9 5.1 5.6 5.6 5.5 5.1 5.7 5.7 5.3 5.2 5.4 5.6 5.7 5.7 5.8 5.6 5.2
 5.5 5.5 5.7 5.7 5.1 6.  5.6 5.8 5.9 5.8 5.9 5.4 5.2 5.9 5.4 5.9 5.7 5.2
 5.5 5.8 5.3 5.7 5.9 5.6 5.9 5.6 5.6 5.7 5.4 5.7 5.4 5.1 5.5 5.9 5.5 5.4
 5.1 5.9 5.6 5.1 5.1 5.4 5.8 5.9 5.3 5.8 6.  5.8 5.2 5.6 5.6 5.9 5.7 6.
 5.8 5.7 5.2 5.7 5.3 5.1 5.7 5.8 5.4 5.4 5.6 5.7 5.9 5.9 5.5 5.7 5.3 5.1
 5.1 5.7 5.5 5.3 5.5 5.4 5.7 5.5 5.1 5.1 5.9 5.3 5.9 5.1 5.7 5.2 5.4 5.1
 5.5 5.4 5.6 5.5 5.5 5.2 5.9 5.4 5.9 5.4 5.3 5.8 5.2 5.8 5.4 5.2 5.4 5.8
 5.8 5.3 5.4 5.3 5.3 5.2 5.1 5.7 5.2 5.3 5.6 5.4 5.2 5.6 5.6 5.7 5.5 5.6
 5.8 5.3 5.4 5.6 5.5 5.6 5.6 5.4 5.3 6.  5.8 5.4 5.8 5.8 5.1 5.3 5.1 6.
 5.5 5.5 5.9 5.6 6.  5.6 5.4 5.1 5.3 5.2 5.3 6.  5.4 5.2 5.8 5.7 5.6 5.2
 5.5 5.5 5.2 5.5 5.3 5.4 5.7 5.1 5.9 5.6 5.2 5.8 5.8 5.1 5.4 5.7 5.7 5.4
 5.7 5.7 5.5 6.  5.7 5.3 5.5 5.3 5.9 5.2 5.7 5.9 5.1 5.6 5.8 5.7 5.6 5.7
 5.6 5.3 5.9 5.2 5.5 5.7 5.2 5.3 5.1 5.3 5.2 5.8 5.3 5.8 5.2 5.5 5.5 5.2
 5.6 5.7 6.  5.7 5.5 5.4 5.1 5.7 5.7 5.5 5.4 5.6 6.  5.4 5.2 5.4 5.6 5.5
 5.4 5.7 5.8 5.2 5.1 5.4 5.9 5.6 5.4 5.5 5.6 5.9 5.6 5.3 5.1 5.6 5.1 5.2
 5.7 5.9 5.1 5.9 5.1 5.3 5.7 5.8 5.3 6.  5.5 5.7 5.4 5.7 5.3 5.7 5.1 5.3
 5.4 5.6 5.9 5.4 5.1 5.1 5.4 5.6 5.9 5.2 5.8 5.5 5.5 5.8 5.6 5.8 5.4 5.9
 5.5 5.3 6.  5.2 5.1 5.9 5.5 5.2 5.5 5.3 5.8 5.6 5.1 5.3 6.  5.1 6.  5.6
 5.9 6.  5.3 6.  5.9 5.8 5.5 5.3 5.5 5.2 5.3 5.7 5.1 5.1 5.1 5.2 5.4 5.8
 5.6 5.9 5.6 5.8 5.3 5.2 5.4 5.4 5.2 5.4 5.1 5.1 5.7 5.5 5.5 5.9 5.5 5.1
 5.2 5.2 6.  5.6 5.9 5.9 5.4 5.3 5.8 5.3 5.7 5.5 5.7 5.4 5.2 5.7 5.2 5.6
 5.4 5.4 5.8 6.  5.7 5.1 5.6 5.8 5.3 5.5 5.4 5.9 5.8 6.  5.1 5.4 5.5 5.8
 5.4 5.5 5.1 5.1 5.9 5.5 5.1 5.6 5.7 5.3 5.1 5.6 5.3 5.4 5.4 5.6 5.8 5.3
 5.7 5.8 5.5 5.2 5.9 5.6 5.3 5.8 5.4 5.6 5.8 5.2 5.8 5.3 5.7 5.8 5.4 5.8
 5.9 5.2 5.3 5.6 5.1 5.4 6.  5.8 5.6 5.1 5.7 6.  5.3 5.8 5.5 5.5 5.4 5.8
 5.5 5.1 5.4 5.2 5.7 5.1 5.4 5.4 6.  5.7 5.9 5.8 5.3 5.5 5.7 5.9 5.8 5.4
 5.3 5.1 5.2 5.1 5.2 5.1 5.5 5.3 5.3 5.4 5.1 5.1 5.9 5.5 5.6 5.1 5.9 5.3
 5.4 5.9 5.1 5.5 5.4 5.7 5.8 5.5 5.4 5.5 5.1 5.6 5.5 5.4 5.5 5.7 5.3 5.2
 5.4 5.9 5.9 5.4 5.4 5.2 5.6 5.7 6.  5.8 5.2 5.5 5.1 5.1 5.1 5.8 5.9 5.3
 6.  5.7 5.9 5.2 5.1 6.  5.3 5.6 5.5 5.6 5.6 5.2 5.2 5.4 5.8 6.  5.9 5.1
 5.7 5.5 5.7 5.2 5.7 5.4 5.2 5.1 6.  5.7 5.1 5.9 5.5 5.6 5.8 5.2 5.7 5.5
 5.7 5.7 5.5 5.1 5.6 5.2 5.8 5.4 5.3 5.6 5.9 5.5 5.5 5.5 5.7 5.8 5.6 5.7
 5.4 5.1 5.1 5.6 5.2 5.7 5.6 5.7 5.3 5.4 5.4 5.9 5.8 5.1 5.9 5.8 5.5 5.6
 5.6 5.7 5.2 5.2 5.2 5.4 5.9 5.9 5.5 5.6 5.2 6.  5.4 5.6 5.8 5.5 5.2 5.7
 5.9 5.5 5.5 5.3 5.3 5.8 5.7 5.7 5.8 5.8 5.2 5.8 5.1 5.3 5.8 5.8 5.1 5.4
 5.3 5.7 5.2 5.8 5.2 5.8 5.5 5.2 5.4 6.  5.9 5.7 5.9 5.8 5.3 5.5 5.8 5.4
 5.4 5.4 5.6 5.3 5.3 5.1 5.9 5.7 5.6 5.7 5.1 5.9 5.2 5.7 5.9 5.6 5.6 5.4
 5.9 5.6 5.6 5.9 5.4 5.8 6.  5.6 5.4 5.7 5.5 5.8 5.7 5.9 5.2 5.1 5.5 5.3
 5.4 5.5 5.6 5.1 5.5 5.9 5.8 5.5 5.5 5.5 5.6 5.6 5.4 5.8 5.9 5.1 5.2 6.
 5.2 5.2 6.  5.1 5.6 5.1 5.2 6.  5.3 5.2 5.8 5.8 5.2 5.1 5.7 5.3 5.8 5.4
 5.1 6.  5.2 5.3 5.6 5.1 5.8 5.6 5.1 5.6 5.7 5.4 5.1 5.8 5.1 5.7 5.2 5.4
 5.9 5.3 5.6 5.1 5.3 5.9 5.9 5.7 5.4 5.8 5.2 5.5 5.2 5.4 5.1 5.4 5.7 5.3
 5.6 5.4 5.7 5.4 5.6 6.  5.4 5.6 5.9 5.9 5.7 5.7 5.9 5.6 5.5 5.4 5.4 6.
 5.2 5.3 5.8 5.4 5.9 5.2 5.9 5.3 5.4 5.9 5.8 5.5 5.8 5.5 5.7 5.8 5.9 5.1
 5.7 6.  5.3 6.  5.6 5.3 5.3 5.2 5.6 5.4 5.3 6.  5.7 5.8 5.5 5.5 5.8 5.3
 5.8 5.4 5.8 5.8 5.6 5.7 5.5 6.  5.6 5.5 5.1 5.9 5.4 5.8 5.8 5.5 5.8 5.7
 5.6 5.6 5.3 5.8 5.8 6.  5.5 5.7 5.6 5.5 5.5 5.7 5.7 5.5 5.8 5.3 5.8 5.2
 5.6 5.6 5.5 5.5 5.2 5.8 5.7 5.9 5.6 5.5 5.5 5.5 5.3 5.6 5.6 5.4 5.3 5.1
 5.3 5.9 5.9 5.5 5.4 5.5 5.9 5.6 5.8 5.2 5.4 5.7 5.3 5.3 5.8 5.8 5.8 5.8
 5.5 5.1 5.1 5.8 5.4 5.5 5.9 5.6]
     Student_ID  Age  Gender  Class  Study_Hours_Per_Day  \
3         S0004   18  Female      9                  5.5
5         S0006   19    Male     12                  5.2
9         S0010   18    Male     10                  5.7
11        S0012   18  Female      9                  5.7
13        S0014   17  Female     10                  5.5
...         ...  ...     ...    ...                  ...
4988      S4989   15  Female     12                  5.8
4991      S4992   15    Male     11                  5.4
4992      S4993   19  Female     10                  5.5
4993      S4994   19    Male      9                  5.9
4996      S4997   19    Male     10                  5.6

      Attendance_Percentage Parental_Education Internet_Access  \
3                        68       Postgraduate             Yes
5                        82        High School              No
9                        97        High School             Yes
11                       74       Postgraduate             Yes
13                       76       Postgraduate              No
...                     ...                ...             ...
4988                     94           Graduate             Yes
4991                     54        High School             Yes
4992                     89           Graduate              No
4993                     58       Postgraduate              No
4996                     90        High School             Yes

     Extracurricular_Activities  Math_Score  Science_Score  English_Score  \
3                            No          68             48             77
5                           Yes          88             70             46
9                            No          72             73             73
11                           No          54             38             59
13                          Yes          79             82            100
...                         ...         ...            ...            ...
4988                         No          81             38             36
4991                        Yes          56             71             38
4992                        Yes          74             57             43
4993                        Yes          54             48             47
4996                         No          44             59             43

      Previous_Year_Score  Final_Percentage Performance_Level Pass_Fail
3                      54             64.33           Average      Pass
5                      60             68.00              Good      Pass
9                      61             72.67              Good      Pass
11                     81             50.33           Average      Pass
13                     71             87.00         Excellent      Pass
...                   ...               ...               ...       ...
4988                   49             51.67           Average      Pass
4991                   77             55.00           Average      Pass
4992                   95             58.00           Average      Pass
4993                   78             49.67              Poor      Fail
4996                   63             48.67              Poor      Fail

[908 rows x 16 columns]

In [42]:
attendance = df['Attendance_Percentage'].values
skor = study_hours * 2 + attendance * 0.5   # kendi uydurduğun bir "başarı skoru" formülü

In [43]:
iki_sutun = df[['Study_Hours_Per_Day','Attendance_Percentage']].values
print(iki_sutun.shape)   # (öğrenci_sayısı, 2)
print(iki_sutun[:, 0])   # sadece çalışma saatleri sütunu

(5000, 2)
[1.  1.6 3.6 ... 2.3 2.9 2. ]

In [44]:
print("Ortalama çalışma saati:", study_hours.mean())
print("Std:", study_hours.std())
print("Min-Max:", study_hours.min(), study_hours.max())

Ortalama çalışma saati: 3.28726
Std: 1.5878197921678643
Min-Max: 0.5 6.0

In [46]:
math_scores = df['Math_Score'].values
print(math_scores[:10])

[40 80 83 68 41 88 75 93 55 72]

In [49]:
notlar_matrisi= df[['Math_Score', 'Science_Score', 'English_Score']].values
print(notlar_matrisi[:10])

[[40 39 72]
 [80 44 35]
 [83 73 59]
 [68 48 77]
 [41 46 36]
 [88 70 46]
 [75 69 64]
 [93 37 48]
 [55 39 83]
 [72 73 73]]

In [51]:
print(notlar_matrisi.shape)
print(notlar_ma trisi.ndim)
print(notlar_matrisi.dtype)

(5000, 3)
2
int64

In [60]:
np.zeros(len(df))
np.arange(0, len(df))
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [62]:
math_scores[0]
math_scores[:5]
notlar_matrisi[:,1]

array([39, 44, 73, ..., 41, 45, 53])

In [63]:
kosul = math_scores >= 90
print(kosul.sum())         # kaç kişi
print(math_scores[kosul])  #notlar
df[math_scores >= 90]      #tüm satırlar

792
[ 93  95 100  97  95  99  95  93  90 100  99  95  91  97  93  91  94  90
  96  94  96  97  96  94  91  93  94  98  99  99  93  96  93  99  94  96
  94  93  95  97 100  96  92  93  94  95  93  91  96  95  98  96  92  98
  97  95 100  94  98  92  93  92  98  91  91  97  96  94  94  92  94  91
  96  91 100  96  97  98  98  95  92  91 100  90  91  93  94  99  99  96
 100  99  98  96  91 100 100  93  92  91  96  95  99  93  92  96  96  91
  97  95  94  98  94  96 100  93  94  95  96  92  91  93  93  99  93  90
  97  92 100 100  91  95  94  92  92  91  94  96  92  96  94  96  90  91
 100 100  97  90  93  98  97  92  95  93  92  92  95 100 100  94  92  91
  97  91  97 100 100 100  90  90  97 100  90  95  93  90  94  91  97  92
 100  94  93  96  92  94  90  99  98  94  91  97  92  97  98  90  93 100
  98  93  95  95  92  95  94 100  94  90  91  98  93 100  90  99  96  93
  95  98  91  91  92  91  98  91  91 100  93  96  99  91  94  98  95  93
  95  97  91  97  93  96 100  93  96  95  94  91  93  90  95  93  94  99
  96  96  97  90  98  99  96  99  98  97  90  96  97  91  99  93  91  98
  90  90  90  96 100  91  90  93  98  96  91  90  90  91  99  96  90  97
  94 100  97  98  96  95  93  95  94  98  92  98  95  97  90  93  96  91
  99  96  97  92  94  93  97  97  95  93  97  92  99  90  91  99 100  96
  95  90  96 100  96  99  93  93  93  90 100  94  97  91  99  95  95  97
  98  98  94  99  95 100  92  91  90 100  93  96  92  93  97  99  99  92
  99 100  92  91  94  94  91  99  96  92  93  90  98  98  97  98  93  99
 100  97  95  98  95  91  92  96  99  95  93  95  97  98  95  95  92  99
  93  96  95  91 100  92  95  94  93  93  99  95  90  97  98  91  99  92
  92  93  91  97  93  93  92  97  95  98  95  99  97 100  96  99  98  97
  91  98  95  98  90  97  96  90  92  92  95  90  94  98  96  92  95  98
  93  90  97  92 100 100  98  98  94 100  91  99  98  94  99  91  98  92
  93  95  95  96  92  94  94  97  97  92  90  92  98  95  90  98  94  96
  93  94  94  96 100  98  92  91  97  92  92  91  99  97  99 100  98 100
  93  90  99  99  96  90  98  97  91  95  90  99  96  92  96  90  92 100
  93  97  93  96  94  93  96  94  95  97  94 100  99  99  97  99  98  91
  95  99  99  92 100 100 100  98  92  96  94  91  98  97  97  95  99  98
  97  91  90  96  97  99  97  95  94  96  97  94 100  91  94  90  97  91
  91 100  90  94  91  92  99  91  96  96  91  97  93  90  90  94  98  91
  91  98  99  95  92  90  92  91  92  90  99  99 100  95  90  92  92  94
  98  96  91  94  95  97 100  98  99  97 100  96  96  94  98  93 100  97
  99  97 100  90  98  92  97  92  99  94  90  99  92  96  93  91  91  95
  99  90  91  95 100  99  99  94  98  97  93  92  93  96  92  92 100  94
  99 100  97  99  96  90  95  98  99  94  98  96  90  92  98  92  95  96
  91  95  98  92  95 100  98  98  90  93  93 100  90  98  93  92  93  92
  92  94  91 100  96  90  96  99  99  98  96  96  94  93  94  92  93  94
  99  90  93  94  99 100  93  99  98  92 100  93  94  95  96  99  94  98
  92  93  96  90  98  91  91  90  92  90  98  97  92  94  90  90  91  97
  97 100  91  99  97 100  90  96  91  94 100  92  99 100  97  96  98  94
  90  93  95  92  95  96 100  95  96  99 100  91  96  96  97  90  90  95]

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail
7,S0008,18,Female,11,2.0,81,Graduate,No,Yes,93,37,48,55,59.33,Average,Pass
10,S0011,14,Female,9,3.6,88,Graduate,Yes,No,95,85,69,41,83.00,Excellent,Pass
21,S0022,15,Male,12,2.8,83,Postgraduate,No,Yes,100,96,99,86,98.33,Excellent,Pass
34,S0035,15,Female,12,2.3,79,Graduate,No,Yes,97,95,53,93,81.67,Excellent,Pass
35,S0036,18,Female,10,3.4,87,High School,No,No,95,86,35,68,72.00,Good,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4963,S4964,19,Female,9,2.7,72,Postgraduate,Yes,No,96,99,58,59,84.33,Excellent,Pass
4974,S4975,17,Male,10,5.1,90,Graduate,No,No,97,55,40,62,64.00,Average,Pass
4977,S4978,14,Male,10,2.6,78,High School,Yes,Yes,90,98,73,66,87.00,Excellent,Pass
4982,S4983,16,Female,10,1.6,83,High School,Yes,No,90,47,95,77,77.33,Good,Pass
4997,S4998,16,Female,9,2.3,61,Graduate,No,No,95,41,82,62,72.67,Good,Pass

In [64]:
math_scores.reshape(-1, 1)   # (5000,) -> (5000,1)

array([[40],
       [80],
       [83],
       ...,
       [95],
       [66],
       [69]])

In [65]:
math_scores + 2              # herkese +2 puan
(df['Math_Score'].values + df['Science_Score'].values + df['English_Score'].values) / 3

array([50.33333333, 53.        , 71.66666667, ..., 72.66666667,
       57.33333333, 69.66666667])

In [66]:
math_scores.mean(), math_scores.std(), math_scores.min(), math_scores.max()
notlar_matrisi.mean(axis=0)   # her dersin sınıf ortalaması
notlar_matrisi.mean(axis=1)   # her öğrencinin kendi ortalaması

array([50.33333333, 53.        , 71.66666667, ..., 72.66666667,
       57.33333333, 69.66666667])